# Generated by Django 4.2.7 on 2024-01-06 14:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import mastermind.fields
import mastermind.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.UUIDField(default=mastermind.models.generate_game_id)),
                ('code', django.contrib.postgres.fields.ArrayField(base_field=mastermind.fields.ColorField(choices=[('red', 'Red'), ('blue', 'Blue'), ('white', 'White'), ('green', 'Green'), ('black', 'Black'), ('yellow', 'Yellow')], max_length=6), default=mastermind.models.generate_code, size=4)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('player',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.UUIDField()),
            ],
            options={
                'ordering': ('player_id',),
            },
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('code', django.contrib.postgres.fields.ArrayField(base_field=mastermind.fields.ColorField(choices=[('red', 'Red'), ('blue', 'Blue'), ('white', 'White'), ('green', 'Green'), ('black', 'Black'), ('yellow', 'Yellow')], max_length=6), size=4)),
                ('hint', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=2)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='mastermind.game')),
            ],
            options={
                'ordering': ('game', 'position'),
            },
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='mastermind.player'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('player', 'is_active'), name='Unique constraint on player and is_active = true'),
        ),
    ]
